package com.wafflestudio.snutt2.views

object NavigationDestination {
    const val Onboard = "onboard"
    const val Tutorial = "tutorial"
    const val Home = "home"
    const val SignIn = "signIn"
    const val SignUp = "signUp"
    const val FindId = "find_id"
    const val FindPassword = "find_password"
    const val EmailVerification = "email_verification"
    const val LecturesOfTable = "lectures_of_table"
    const val LectureDetail = "lecture_detail"
    const val LectureColorSelector = "lecture_color_selector"
    const val Notification = "notifications"
    const val AppReport = "app_report"
    const val ServiceInfo = "service_info"
    const val TeamInfo = "team_info"
    const val TimeTableConfig = "timetable_config"
    const val UserConfig = "user_config"
    const val ChangeNickname = "change_nickname"
    const val PersonalInformationPolicy = "personal_information_policy"
    const val ThemeModeSelect = "theme_mode_select"
    const val Bookmark = "bookmark"
    const val NetworkLog = "network_log"
    const val VacancyNotification = "vacancy"
    const val Friends = "friends"
    const val ThemeConfig = "theme_config"
    const val CustomThemeDetail = "custom_theme_detail"
    const val BuiltInThemeDetail = "builtin_theme_detail"
}
