name: CD

on:
  push:
    branches:
      - 'release-*'
    paths:
      - 'version.properties'

jobs:
  build-live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Clean build
        run: ./gradlew clean
      - name: Setup google-services.json (Live)
        run: |
          mkdir -p ./app/src/live
          cat << EOF > ./app/src/live/google-services.json
          ${{ secrets.google_services_json_live }}
          EOF
      - name: Setup gcp-service-account.json (Live)
        run: |
          cat << EOF > ./gcp-service-account-live.json
          ${{ secrets.app_distribution_service_account_live }}
          EOF
      - name: Setup secrets.xml (Live)
        run: |
          mkdir -p ./app/src/live/res/values
          cat << EOF > ./app/src/live/res/values/secrets.xml
          ${{ secrets.secrets_xml_live }}
          EOF
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          mkdir -p ./app/keystore
          echo $ENCODED_STRING | base64 -di > ./app/keystore/android.jks
      - name: Build production apk
        run: ./gradlew bundleLiveRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload artifact to Firebase App Distribution
        run: ./gradlew appDistributionUploadLiveRelease
      - name: Set Message
        run: |
          PROPERTY=$(head -n 1 version.properties)
          VERSION="${PROPERTY/snuttVersionName=}"
          TITLE="SNUTT Android 빌드 알림"
          MESSAGE="${VERSION} 빌드 완료"
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ${{ env.TITLE }}
          SLACK_MESSAGE: ${{ env.MESSAGE }}
          SLACK_USERNAME: BuildNoti

  build-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Clean build
        run: ./gradlew clean
      - name: Setup google-services.json (Staging)
        run: |
          mkdir -p ./app/src/staging
          cat << EOF > ./app/src/staging/google-services.json
          ${{ secrets.google_services_json_staging }}
          EOF
      - name: Setup gcp-service-account.json (Staging)
        run: |
          cat << EOF > ./gcp-service-account-staging.json
          ${{ secrets.app_distribution_service_account_staging }}
          EOF
      - name: Setup secrets.xml (Staging)
        run: |
          mkdir -p ./app/src/staging/res/values
          cat << EOF > ./app/src/staging/res/values/secrets.xml
          ${{ secrets.secrets_xml_staging }}
          EOF
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          mkdir -p ./app/keystore
          echo $ENCODED_STRING | base64 -di > ./app/keystore/android.jks
      - name: Build production apk
        run: ./gradlew assembleStagingRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload artifact to Firebase App Distribution
        run: ./gradlew appDistributionUploadStagingRelease
      - name: Slack Upload APK
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channels: ${{ secrets.SLACK_DEPLOY_CHANNEL }}
          file_path: './app/build/outputs/apk/staging/release/app-staging-release.apk'
          file_name: 'app-staging-release.apk'
          file_type: 'apk'
          initial_comment: 'staging-release APK'
