name: CI

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - name: Setup secrets
        uses: ./.github/actions/setup-secrets
        with:
          variant: staging
          google_services_json: ${{ secrets.google_services_json_staging }}
          secrets_xml_app: ${{ secrets.secrets_xml_staging }}
      - name: Run ktlint
        run: ./gradlew ktlintCheck --stacktrace
      - name: Upload ktlint report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ktlint-result
          path: ./**/build/reports/ktlint/**/*.html

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - name: Setup secrets
        uses: ./.github/actions/setup-secrets
        with:
          variant: staging
          google_services_json: ${{ secrets.google_services_json_staging }}
          secrets_xml_app: ${{ secrets.secrets_xml_staging }}
      - name: Build debug APK, run unit tests, run lint
        run: ./gradlew assembleStagingDebug testStagingDebugUnitTest lintStagingDebug --stacktrace
      - name: Upload unit test report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-test-report
          path: ./**/build/reports/tests/**
      - name: Upload lint report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: lint-report
          path: ./**/build/reports/lint-results-*.html
