name: CI

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup secrets
        uses: ./.github/actions/setup-secrets
        with:
          variant: staging
          google_services_json: ${{ secrets.google_services_json_staging }}
          secrets_xml_app: ${{ secrets.secrets_xml_staging }}
      - name: Run ktlint and build debug APK
        run: ./gradlew ktlintCheck assembleStagingDebug --stacktrace
      - name: Run unit tests
        run: ./gradlew testStagingDebugUnitTest --stacktrace
      - name: Upload ktlint report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ktlint-result
          path: ./**/build/reports/ktlint/**/*.html
