name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: 'live / dev'
        required: true
        options:
          - live
          - dev
      firebase:
        type: boolean
        description: Upload artifact to Firebase
      slack:
        type: boolean
        description: Send artifact to slack
      slack_message:
        type: string
        description: Message to send with artifact

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'jetbrains'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Setup secrets (Live)
        if: github.event.inputs.variant == 'live'
        uses: ./.github/actions/setup-secrets
        with:
          variant: live
          google_services_json: ${{ secrets.google_services_json_live }}
          secrets_xml_app: ${{ secrets.secrets_xml_live }}
          gcp_service_account: ${{ secrets.app_distribution_service_account_live }}
          keystore_base64: ${{ secrets.KEYSTORE }}
      - name: Setup secrets (Dev)
        if: github.event.inputs.variant == 'dev'
        uses: ./.github/actions/setup-secrets
        with:
          variant: dev
          google_services_json: ${{ secrets.google_services_json_dev }}
          secrets_xml_app: ${{ secrets.secrets_xml_dev }}
          gcp_service_account: ${{ secrets.app_distribution_service_account_dev }}
          keystore_base64: ${{ secrets.KEYSTORE }}
      - name: Build production apk (Live)
        if: github.event.inputs.variant == 'live'
        run: ./gradlew bundleLiveRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Build production apk (Dev)
        if: github.event.inputs.variant == 'dev'
        run: ./gradlew assembleDevRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload artifact to Firebase App Distribution (Live)
        if: ${{ github.event.inputs.firebase == 'true' && github.event.inputs.variant == 'live' }}
        run: ./gradlew appDistributionUploadLiveRelease
      - name: Upload artifact to Firebase App Distribution (Dev)
        if: ${{ github.event.inputs.firebase == 'true' && github.event.inputs.variant == 'dev' }}
        run: ./gradlew appDistributionUploadDevRelease
      - name: Slack Notification
        if: ${{ github.event.inputs.slack == 'true' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: SNUTT Android 빌드 알림
          SLACK_MESSAGE: ${{ github.event.inputs.slack_message }}
          SLACK_USERNAME: BuildNoti
      - name: Slack Upload APK (Live)
        if: ${{ github.event.inputs.slack == 'true' && github.event.inputs.variant == 'live' }}
        uses: MeilCli/slack-upload-file@v5
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channel_id: ${{ secrets.SLACK_DEPLOY_CHANNEL_ID }}
          file_path: './app/build/outputs/apk/live/release/app-live-release.apk'
          file_name: 'app-live-release.apk'
          file_type: 'apk'
          initial_comment: 'live-release APK'
      - name: Slack Upload APK (Dev)
        if: ${{ github.event.inputs.slack == 'true' && github.event.inputs.variant == 'dev' }}
        uses: MeilCli/slack-upload-file@v5
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channel_id: ${{ secrets.SLACK_DEPLOY_CHANNEL_ID }}
          file_path: './app/build/outputs/apk/dev/release/app-dev-release.apk'
          file_name: 'app-dev-release.apk'
          file_type: 'apk'
          initial_comment: 'dev-release APK'
